name: Generate JSON Schemas

on:
  push:
    branches: [ "main" ]

jobs:
  generate-schema:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - uses: pnpm/action-setup@v2
      with:
        version: 8
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'pnpm'
    - name: Install dependencies
      run: pnpm install --frozen-lockfile
    - name: Generate Schemas
      run: pnpm generate
    - name: Push updated Schemas
      run: |
        set +e
        git config user.name github-actions[bot]
        git config user.email 41898282+github-actions[bot]@users.noreply.github.com
        git add --all
        git commit -m "Update JSON Schemas - [Skip GitHub Action]"
        git push
        set -e
